name: C/C++ CI

on: [push]

env:
  DOC_ROOT: ${{ github.workspace }}/ACE
  ACE_ROOT: ${{ github.workspace }}/ACE/ACE
  MPC_ROOT: ${{ github.workspace }}/ACE/MPC
  TAO_ROOT: ${{ github.workspace }}/ACE/TAO
  X11_BASE_ROOT: ${{ github.workspace }}/axcioma
  RIDL_ROOT: ${{ github.workspace }}/ridl
  TAOX11_ROOT: ${{ github.workspace }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [GCC8Ruby27,
               GCC9Ruby27]
        include:
          - name: GCC8Ruby27
            os: ubuntu-latest
            CC: gcc-8
            CXX: g++-8
            RubyVersion: 2.7
          - name: GCC9Ruby27
            os: ubuntu-latest
            CC: gcc-9
            CXX: g++-9
            RubyVersion: 2.7
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
      ruby-version: $RubyVersion
    - name: Add repository $Repo
      if: $Repo != ''
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
        sudo apt-add-repository "deb http://apt.llvm.org/$(lsb_release -cs)/ $Repo main"
      fi
    - name: git clone dependent repositories
      run: |
        git clone --depth 1 --branch Latest_Micro  git://github.com/DOCGroup/ACE_TAO.git $DOC_ROOT
        git clone --depth 1 --branch Latest_ACETAO_Micro  git://github.com/DOCGroup/MPC.git $MPC_ROOT
        git clone --depth 1 git://github.com/RemedyIT/axcioma.git $X11_BASE_ROOT
        git clone --depth 1 git://github.com/RemedyIT/ridl.git $RIDL_ROOT
    - name: Run brix11 configure
      run: |
        $X11_BASE_ROOT/bin/brix11 configure -W aceroot=$ACE_ROOT -W taoroot=$TAO_ROOT -W mpcroot=$MPC_ROOT
    - name: Print brix11 configuration
      run: |
        $X11_BASE_ROOT/bin/brix11 env -- configure -P
    - name: Run brix11 gen build
      run: |
        $X11_BASE_ROOT/bin/brix11 gen build axcioma/workspace.mwc -- gen build $TAOX11_ROOT/examples -- gen build $TAOX11_ROOT/orbsvcs/tests -- gen build $TAOX11_ROOT/tests
    - name: Run brix11 make
      run: |
        $X11_BASE_ROOT/bin/brix11 make -N -d $X11_BASE_ROOT -- make -N -d $TAOX11_ROOT/examples -- make -N -d $TAOX11_ROOT/orbsvcs/tests -- make -N -d $TAOX11_ROOT/tests
