name: windows

on:
  push:
    branches:
      - feature/*
      - master
      - v*
    tags:
      - AXCIOMA-v*
  pull_request:
    branches:
      - develop
      - master
      - v*
  schedule:
    - cron: '0 1 * * SUN'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  DOC_ROOT: ${{ github.workspace }}/ACE_TAO
  ACE_ROOT: ${{ github.workspace }}/ACE_TAO/ACE
  TAO_ROOT: ${{ github.workspace }}/ACE_TAO/TAO
  MPC_ROOT: ${{ github.workspace }}/ACE_TAO/MPC
  X11_BASE_ROOT: ${{ github.workspace }}/axcioma
  RIDL_ROOT: ${{ github.workspace }}/ridl
  TAOX11_ROOT: ${{ github.workspace }}
  X11_BRANCH: 0ab17f33349e9b7fe2892d865ea9f7e0d3c3478b # (AXCIOMA_v2.4.0~10)
  ACETAOMPC_BRANCH: ACE+TAO-7_0_11 # Latest_ACE7TAO3_Micro

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2019
            ruby: '3.1'
            project_type: vs2019
          - os: windows-2022
            ruby: '3.2'
            project_type: vs2019
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} ruby-${{ matrix.ruby }} ${{ matrix.project_type }}
    steps:
      - if: contains(fromJson('["pull_request", "pull_request_target"]'), github.event_name) && github.repository_owner == 'RemedyIT'
        run: |
          echo "X11_BRANCH=${{ github.base_ref }}" >> $GITHUB_ENV
      - if: contains(fromJson('["pull_request", "pull_request_target"]'), github.event_name) == false && github.repository_owner == 'RemedyIT'
        run: |
          echo "X11_BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: checkout ACE_TAO
        uses: actions/checkout@v3
        with:
          repository: DOCGroup/ACE_TAO
          path: ${{ env.DOC_ROOT }}
          ref: ${{ env.ACETAOMPC_BRANCH }}
      - name: checkout MPC
        uses: actions/checkout@v3
        with:
          repository: DOCGroup/MPC
          path: ${{ env.MPC_ROOT }}
          ref: ${{ env.ACETAOMPC_BRANCH }}
      - name: checkout ridl
        uses: actions/checkout@v3
        with:
          repository: RemedyIT/ridl
          path: ${{ env.RIDL_ROOT }}
          ref: 42290ed847ce4a960e8306c8fcf87db0cf65c8b5 # ${{ env.X11_BRANCH }}
      - name: checkout axcioma
        uses: actions/checkout@v3
        with:
          repository: RemedyIT/axcioma
          path: ${{ env.X11_BASE_ROOT }}
          ref: ${{ env.X11_BRANCH }}
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - uses: shogo82148/actions-setup-perl@v1
        with:
          distribution: strawberry
      - name: Run brix11 configure
        run: |
          %X11_BASE_ROOT%\bin\brix11 -t ${{ matrix.project_type }} configure -W aceroot=%ACE_ROOT% -W taoroot=%TAO_ROOT% -W mpcroot=%MPC_ROOT%
        shell: cmd
      - name: Print brix11 configuration
        run: |
          %X11_BASE_ROOT%/bin/brix11 env -- configure -P
        shell: cmd
      - name: Run brix11 gen build --static
        run: |
          %X11_BASE_ROOT%/bin/brix11 gen build --static axcioma/workspace.mwc -- gen build --static %TAOX11_ROOT%/examples -- gen build --static %TAOX11_ROOT%/orbsvcs/tests -- gen build --static %TAOX11_ROOT%/tests
        shell: cmd
      - name: Run brix11 make --release
        run: |
          %X11_BASE_ROOT%/bin/brix11 make --release -N -d %X11_BASE_ROOT% -- make --release -N -d %TAOX11_ROOT%/examples -- make --release -N -d %TAOX11_ROOT%/orbsvcs/tests -- make --release -N -d %TAOX11_ROOT%/tests
        shell: cmd
